### ISSUE TITLE
EDA: data frame report on intended dataset

### ISSUE THREAD

**Issue by phoebewong** [phoebewong/AC297r_2019_Associated_Press#5]
EDA

**Comment by phoebewong** [comment]
If we have the full text, I can do a histogram of named entities extracted from all the full text

**Comment by kareenaaahuang** [comment]
complete for subject tags, need to extract person and organisation tags

**Comment by phoebewong** [comment]
@kareenaaahuang moving this for this week, during the milestone 1 with Pavlos, he also asked for the following viz, do you think you will be able to do those?

1. EDA for other sections

- We showed only "Subject" tags, can we add EDA for tags of other sections too?

2. Reverse order (of image vs article tag)
